import PDFDocument from 'pdfkit';
import fs from 'fs';

export async function generateReport(filePath: string, sessionData: any): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        bufferPages: true,
        margin: 50,
        size: 'A4'
      });

      const stream = fs.createWriteStream(filePath);

      doc.pipe(stream);

      // Header with logo
      doc.fontSize(24).font('Helvetica-Bold').text('MCS - DIAGNOSTICS ENTERPRISE', { align: 'center' });
      doc.fontSize(12).font('Helvetica').text('Professional Android GSM Diagnostic Report', { align: 'center' });
      doc.fontSize(10).text('Offline Local Diagnostics System', { align: 'center' });

      doc.moveTo(50, doc.y + 10).lineTo(545, doc.y + 10).stroke();
      doc.moveDown();

      // Session Info
      const device = sessionData.device || {};
      const startTime = new Date(sessionData.startedAt || Date.now());
      const endTime = sessionData.completedAt ? new Date(sessionData.completedAt) : new Date();
      const duration = (endTime.getTime() - startTime.getTime()) / 1000;

      doc.fontSize(14).font('Helvetica-Bold').text('DIAGNOSTIC SESSION REPORT', { underline: true });
      doc.fontSize(11).font('Helvetica');

      doc.text(`Session ID: ${sessionData.sessionId || 'N/A'}`, { indent: 20 });
      doc.text(`Date: ${startTime.toLocaleString()}`, { indent: 20 });
      doc.text(`Duration: ${duration.toFixed(1)}s`, { indent: 20 });
      doc.moveDown();

      // Device Information
      doc.fontSize(12).font('Helvetica-Bold').text('DEVICE INFORMATION');
      doc.fontSize(11).font('Helvetica');

      doc.text(`Device Model: ${device.model || 'Unknown'}`, { indent: 20 });
      doc.text(`Serial Number: ${device.serial || 'Unknown'}`, { indent: 20 });
      doc.text(`Android Version: ${device.androidVersion || 'Unknown'}`, { indent: 20 });
      doc.text(`Manufacturer: ${device.manufacturer || 'Unknown'}`, { indent: 20 });
      doc.text(`Brand: ${device.brand || 'Unknown'}`, { indent: 20 });
      doc.moveDown();

      // Diagnostic Results
      const results = sessionData.results || [];
      const passCount = results.filter((r: any) => r.status === 'PASS').length;
      const failCount = results.filter((r: any) => r.status === 'FAIL').length;
      const skipCount = results.filter((r: any) => r.status === 'SKIPPED' || r.status === 'NOT_AVAILABLE').length;

      doc.fontSize(12).font('Helvetica-Bold').text('TEST RESULTS SUMMARY');
      doc.fontSize(11).font('Helvetica');

      doc.text(`Total Tests: ${results.length}`, { indent: 20 });
      doc.text(`Passed: ${passCount}`, { indent: 20, color: '#00AA00' });
      doc.text(`Failed: ${failCount}`, { indent: 20, color: failCount > 0 ? '#FF0000' : '#000000' });
      doc.text(`Skipped: ${skipCount}`, { indent: 20 });
      doc.moveDown();

      // Detailed Results
      doc.fontSize(12).font('Helvetica-Bold').text('DETAILED TEST RESULTS');
      doc.fontSize(10);

      results.forEach((result: any, index: number) => {
        const statusColor = result.status === 'PASS' ? '#00AA00' : result.status === 'FAIL' ? '#FF0000' : '#666666';
        const statusStr = result.status || 'UNKNOWN';

        doc.font('Helvetica-Bold').text(`${index + 1}. ${result.name || result.testId}`, {
          indent: 20
        });

        doc.font('Helvetica').text(`Status: ${statusStr}`, {
          indent: 40,
          color: statusColor
        });

        if (result.duration) {
          doc.text(`Duration: ${result.duration}ms`, { indent: 40 });
        }

        if (result.metrics) {
          Object.entries(result.metrics).forEach(([key, value]) => {
            doc.text(`${key}: ${value}`, { indent: 40 });
          });
        }

        if (result.message) {
          doc.text(`Note: ${result.message}`, { indent: 40, color: '#666666' });
        }

        doc.moveDown(0.3);
      });

      doc.moveDown();

      // Technician Information
      doc.fontSize(11).font('Helvetica-Bold').text('TECHNICIAN INFORMATION');
      doc.fontSize(10).font('Helvetica');

      const technicianName = sessionData.technician || '__________________';
      doc.text(`Technician: ${technicianName}`);
      doc.text(`Date: ${new Date().toLocaleDateString()}`);
      doc.moveDown();

      // Notes
      if (sessionData.notes) {
        doc.fontSize(11).font('Helvetica-Bold').text('NOTES');
        doc.fontSize(10).font('Helvetica').text(sessionData.notes);
        doc.moveDown();
      }

      // Footer
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.fontSize(9).font('Helvetica').text('© MCS - DIAGNOSTICS ENTERPRISE | Professional Service Tool', {
        align: 'center'
      });
      doc.text('This report was generated by MCS Diagnostic System for professional use only', {
        align: 'center'
      });

      doc.end();

      stream.on('finish', () => {
        resolve();
      });

      stream.on('error', (error) => {
        reject(error);
      });
    } catch (error) {
      reject(error);
    }
  });
}
